# ===================================
# docker-compose.yml
# ===================================
version: '3.8'

services:
  app:
    build: .
    container_name: contract-manager
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - DEBUG=${DEBUG:-False}
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./templates:/app/templates
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge